"""资料用例真正消费的读取和归档接口，保持标准库可用。"""

from typing import Protocol, Mapping, Iterable
from .domain import AdmissionEvidence, AdmissionSnapshot, CoreData, InspectionInputs, MarketEvidence, StockEvidence, ReadReceipt, DataIssue


class MarketSource(Protocol):
    def inspection_inputs(self) -> InspectionInputs: ...
    def read_core(self) -> CoreData: ...
    def read_market(self, symbol: str, monthly: bool = False) -> MarketEvidence: ...
    def read_stock(self, stock: Mapping, monthly: bool = False) -> StockEvidence: ...
    def enforce(self, hashes: Mapping[str, str]) -> None: ...
    def input_refs(self, core: CoreData) -> tuple[tuple[str, str], ...]: ...
    def verify_current(self, snapshot: AdmissionSnapshot) -> None: ...
    def verify_unchanged(self) -> ReadReceipt: ...


class AdmissionArchive(Protocol):
    def read_evidence(self, selection: Mapping) -> AdmissionEvidence: ...
    def initialize(self) -> None: ...
    def append_issues(self, issues: Iterable[DataIssue]) -> None: ...
    def write_coverage(self, coverage: list[dict], samples: list[dict]) -> None: ...
    def finish(self, result: dict, receipt: ReadReceipt, execution: Mapping) -> None: ...


class AdmittedReader(Protocol):
    snapshot: AdmissionSnapshot
    def read_market_facts(self, symbol: str): ...
    def iter_stock_facts(self): ...
    def verify_current(self) -> None: ...
    def verify_unchanged(self) -> ReadReceipt: ...
