"""次日上涨分类所需的模型和归档接口。"""

from typing import Protocol
from daily_return.experiments import FoldDescription
from .domain import ClassificationSettings


class FittedModel(Protocol):
    summary: dict
    def predict(self, features): ...
    def export_text(self) -> str: ...
    def feature_usage(self): ...


class ModelTrainer(Protocol):
    def fit(self, train_x, train_y, valid_x, valid_y, names, settings: ClassificationSettings) -> FittedModel: ...
    def check_reload(self, text: str, names, features, expected): ...


class FinalTrainer(Protocol):
    def fit_fixed(self, train_x, train_y, names, settings: ClassificationSettings) -> FittedModel: ...
    def check_reload(self, text: str, names, features, expected): ...


class ValidationArchive(Protocol):
    def begin(self, description: FoldDescription, configuration) -> None: ...
    def fitted(self, model: FittedModel, boundaries) -> None: ...
    def predictions(self, rows, values) -> None: ...
    def predictions_finished(self) -> None: ...
    def evaluated(self, truth, prediction, metrics) -> None: ...
    def finish(self, result, receipt, issues, resources) -> None: ...
